#insert test template DO NOT EDIT THIS FILE, It exists to have a repeatable first test, and all tests in tests/webpages/Scorepage/ImplementationsTest.php use these values
INSERT INTO scoreboard_dba.users VALUES (0,'test1', 1,'password', '001001001');
INSERT INTO scoreboard_dba.fractions VALUES (0011100, 0.0011100, 9999999);