<?php


#echo "Connection successful.";
# So what the following does is effectively makes a second table where there is a counter column called score_rank
# because mysql has deprecated the simple version of this that might be buggy sometimes instead of fixing it so we can
# have a normal ranking column because "ouh mah-hai, it's a QUERY language you shouldn't put your *rank* on the table".
# This means I can't just have the ranks on the table and auto-update with an incrementor every time a row is added
# which would allow me to pull ranks directly by number or username, That would be too simple, of course.
# So instead of auto-updating with a simple in-query incrementor I now have to query it to:
# 1) Generate a second temporary table off of the username (That's the first line) from the original table (line 2)
# 2) Join these two together by comparing the scores to *themselves* (i.e. the score_rank column on t2 is generated by
#    literally taking the row number after the table has been ordered by "how many user scores are higher than or equal
#    to the user score being looked at,
# 3) Select the username in question when applicable
# 4) include columns not referenced in the where clause in the group by (group by is used for the aggregation of results)
# 5) finally order the thing by the score_rank. but we can't SELECT by the score rank because that would be too easy.


#######################################################################################################################
## This class offers all functions for the user database and fraction database, despite the name. oops.
## Common user error checking can be accomplished by checking the types of dynamically
#######################################################################################################################
class scoreDatabaseFunctions
{
    //constructor for a ranking board
    public $ranking;
    public $dbconn;
    //constructor for a ranking board, sets values of $this->dbconn and $this->ranking, for use in scoreboards
    function __construct(){
        $this->makeConnection();
        $this->rankingTable();
    }
    //Connects to the database
    function makeConnection(){
        //This sets the connection up, also has the password included
        $servername = "127.0.0.1";
        $sqlusername = "siteuser";
        $sqlpassword = "edcvfr43edcvfr4";
        $dbname = "scoreboard_dba";
        //these variables are for status reporting
        $connectionstatus = "Connection not attempted.";
        $connectbool = false;
        mysqli_report(MYSQLI_REPORT_STRICT | MYSQLI_REPORT_ALL);
        try {
            // Create connection, username and pw here are for the sql server
            $this->dbconn = mysqli_connect($servername, $sqlusername, $sqlpassword, $dbname);
            // Check connection and report errors
            error_reporting(E_ALL);
            mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);
            $connectionstatus = "Connection Successful.";
            $connectbool = true;
        } catch (mysqli_sql_exception $e){
            $connectionstatus = "Connection to server failed";
            echo $connectionstatus;
        }
    }
    //function to make an initial ranking table.
    function rankingTable(){
        $this->ranking = mysqli_query($this->dbconn, "SELECT users.user_name, users.user_score, users.digits, count(t2.user_name) score_rank
                FROM users
                LEFT JOIN users t2 ON t2.user_score >= users.user_score
                GROUP BY user_name, user_score, digits
                ORDER BY score_rank;");
    }
    //function to retrieve pre-existing digits strings, it returns a string as a status note, and changes public variables
    function retrieveDigits(mysqli $dbconn, $digits){
        //This is basic security to prevent code injection
        $digits = mysqli_real_escape_string($dbconn, $digits);

        //we turn currentDigits into a mysqli_query that the information can be pulled from
        $currentDigits = mysqli_query($dbconn, "SELECT divisor, fraction 
                FROM scoreboard_dba.fractions 
                WHERE digits = ('$digits');");
        //return status code or score
        if($currentDigits->num_rows < 1){
            return " This is the first time these digits have been generated. ";
        }
        else{
            return $currentDigits;
        }
        return "ERROR: Incorrect database permissions or disconnection.";
    }
    //function to retrieve a specific user's score, it returns a string as a status note, and changes public variables
    //check if is_string (Not !is_string) for error message
    function retrieveUserScore(mysqli $dbconn, $username){
        //this is security to prevent code injection
        $username = mysqli_real_escape_string($dbconn, $username);
        //we turn currentScore into a mysqli_query that the information can be pulled from
        $currentScore = mysqli_query($dbconn, "SELECT user_score 
                FROM scoreboard_dba.users 
                WHERE user_name = ('$username');");
        //return status codes
        if($currentScore->num_rows < 1){
            return " User does not exist. ";
        }
        else{
            return $currentScore;
        }
    }
    //function to add a new user, dbconn must be mysqli, Additionally, error checking for pre-existing user is
    //carried out by checking if !is_string($this->addNewUser)
    function addNewUser(mysqli $dbconn, string $newname, string $newpass){
        //this is security to prevent code injection
        $newname = mysqli_real_escape_string($dbconn, $newname);
        $newpass = mysqli_real_escape_string($dbconn, $newpass);
        $userChecker = mysqli_query($dbconn, "SELECT * FROM scoreboard_dba.users WHERE user_name = ('$newname')");
        if($userChecker->num_rows > 0){
            return $userChecker;
        }
        else{
            $newuser = mysqli_query($dbconn, "INSERT INTO scoreboard_dba.users VALUES (0,('$newname'), 0, ('$newpass'), '0')");
            return "Successful new user insertion.";
        }
    }
    function addNewDigits(mysqli $dbconn, string $newDigits, float $newFrac, int $newDivisor){
        //this is security to prevent code injection
        $newDigits = mysqli_real_escape_string($dbconn, $newDigits);
        if ((int)$newDigits > 999999999 || (int)$newDigits < 0){
            return "digits out of bounds";
        }
        if ($newFrac > 1 || $newFrac < 0){
            return "Fraction out of bounds, math implemented incorrectly.";
        }
        $digitsChecker = mysqli_query($dbconn, "SELECT * FROM scoreboard_dba.fractions WHERE digits = ('$newDigits')");
        if($digitsChecker->num_rows > 0){
            return "Digits already exist";
        }
        else{
            $newDigits = mysqli_query($dbconn, "INSERT INTO scoreboard_dba.fractions VALUES (('$newDigits'), $newFrac, $newDivisor)");
            return "Successful new digits insertion";
        }
    }
    //Function to change user score and most recent input digits, digits should START as an int, and then be cast to
    //A string before being put into this.
    function setUserScore(mysqli $dbconn, string $name, int $userscore, string $digits){
        $name = mysqli_real_escape_string($dbconn, $name);
        $digits = mysqli_real_escape_string($dbconn, $digits);
        $scoreCheck = mysqli_query($dbconn, "SELECT user_score 
                FROM scoreboard_dba.users 
                WHERE user_name = ('$name');");
        //return status codes
        if($scoreCheck->num_rows < 1){
            return " User does not exist. ";
        }
        $scoreCheck = mysqli_query($dbconn, "SELECT user_score 
                FROM scoreboard_dba.users 
                WHERE user_name = ('$name') AND ('$userscore') > user_score;");
        if($scoreCheck->num_rows < 1){
            return " Not higher than your current highest score, too bad! ";
        }
        $scoreUpdate = mysqli_query($dbconn, "UPDATE scoreboard_dba.users 
        SET user_score = ('$userscore'),
            digits = ('$digits')
            WHERE user_name = ('$name') AND ('$userscore') > user_score;");
        return $userscore;
    }
    //function to change user's password
    function changePass(mysqli $dbconn, string $name, string $oldpass, string $newpass){
        //input sanitization
        $name = mysqli_real_escape_string($dbconn, $name);
        $oldpass = mysqli_real_escape_string($dbconn, $oldpass);
        $newpass = mysqli_real_escape_string($dbconn, $newpass);
        //check for user existence
        $passfinder = mysqli_query($dbconn, "SELECT user_score 
                FROM scoreboard_dba.users 
                WHERE user_name = ('$name');");
        //return status codes
        if($passfinder->num_rows < 1){
            return " User does not exist. ";
        }
        //check for old password being correct
        $passfinder = mysqli_query($dbconn, "SELECT user_score 
                FROM scoreboard_dba.users 
                WHERE user_name = ('$name') AND password = ('$oldpass');");
        if($passfinder->num_rows < 1){
            return " Incorrect Password ";
        }
        //check if it's the same password
        $passfinder2 = mysqli_query($dbconn, "SELECT user_score 
                FROM scoreboard_dba.users 
                WHERE user_name = ('$name') AND password = ('$newpass');");
        if($passfinder2->num_rows > 0){
            return " This is already your Password ";
        }
        //finally, change the password
        $passfinder = mysqli_query($dbconn, "UPDATE scoreboard_dba.users 
        SET password = ('$newpass')
        WHERE user_name = ('$name') AND password = ('$oldpass');");
        return $passfinder;
    }
    //Function to delete a user
    function deleteUser(mysqli $dbconn, $name, $pass){
        //First query to find the entry password for this user and check for correct permissions
        $name = mysqli_real_escape_string($name);
        $pass = mysqli_real_escape_string($pass);
        $passfinder = mysqli_query($dbconn, "SELECT users.password
            FROM users
            WHERE users.user_name=('$name')
            ");
        if ($passfinder->num_rows != 1){
            return $passfinder;
        }
        $row = mysqli_fetch_array($passfinder);
        if ($row["password"] != $pass) {
            return $row;
        }
        //the second block is to find out if the user exists with the if statement, then check if the password is correct
        mysqli_query($dbconn, "DELETE FROM scoreboard_dba.users
            WHERE user_name = ('$name') AND password = ('$pass');");
        return "Successfully deleted";
    }

}